Popup connected
hafslundnett/hal-components pull request #10
Opened 2019-11-05 07:32 UTC by frideska

2019-11-05 07:46 UTC, Martinesp approved these changes

2019-11-05 15:09 UTC, JGH153 requested changes
Noen små saker så er vi i mål 🥅

2019-11-05 15:09 UTC, JGH153 commented on projects/hal-components/src/lib/components/popup-connected/popup-connected.component.ts
> +  wewValuerelativePositionY() {
Skrivefeil

2019-11-05 15:09 UTC, JGH153 commented on src/app/docs-pages/popup-connected-doc/popup-connected-doc.component.html
> +            <div class="hdd-card popup-container">
Kortet bør være egen komponent i dette eksempelet

2019-11-05 15:09 UTC, JGH153 commented on projects/hal-components/src/lib/components/popup-connected/popup-connected.component.ts
> +  set relativePositionY(relativePositionY: popupPosition) {
get og set bør skrives om til ngOnChanges. Bare spørr meg om dette

2019-11-05 15:09 UTC, JGH153 commented on src/app/docs-pages/popup-connected-doc/popup-connected-doc.component.ts
> +    { apiInput: '(close)', description: 'Output that closes the popup if the a condition is set to true. The popup will close on default by clicking the close button.' },
flytter du output til bunn av listen

2019-11-05 15:09 UTC, JGH153 commented on src/app/docs-pages/popup-connected-doc/popup-connected-doc.component.html
> +      <code><pre>import {{ '{' }} PopupConnectedModule {{ '}' }} from '@hafslundnett/hal-components';</pre></code>
Bør si noe om at de må importere OverlayModule fra cdk

2019-11-05 15:09 UTC, JGH153 commented on src/app/docs-pages/popup-connected-doc/popup-connected-doc.component.ts
> +  <button type="button" (click)="isOpen = !isOpen" class="hdd-button" cdkOverlayOrigin #trigger2="cdkOverlayOrigin">
mulig vi bør ha et mer forklarende navn enn trigger2 🤔

2019-11-06 07:37 UTC, frideska commented on src/app/docs-pages/popup-connected-doc/popup-connected-doc.component.ts
> +  <button type="button" (click)="isOpen = !isOpen" class="hdd-button" cdkOverlayOrigin #trigger2="cdkOverlayOrigin">
Ja, der hadde jeg ikke rettet opp meg selv 😅

2019-11-06 07:38 UTC, frideska commented on src/app/docs-pages/popup-connected-doc/popup-connected-doc.component.html
> +            <div class="hdd-card popup-container">
Hm, dette er gammel kode... Ligger i et eget komponent!

2019-11-06 07:40 UTC, frideska commented on src/app/docs-pages/popup-connected-doc/popup-connected-doc.component.html
> +      <code><pre>import {{ '{' }} PopupConnectedModule {{ '}' }} from '@hafslundnett/hal-components';</pre></code>
Bare la det til som en ny import linje, er det greit?

2019-11-06 09:46 UTC, JGH153 approved these changes

2019-11-06 09:46 UTC, merged