Auto complete highlghter
hafslundnett/hal-components pull request #104
Opened 2020-01-30 12:19 UTC by Martinesp

# PR Checklist

## What type of change is this?
- [ ] Internal (Does not need to be published)
- [X ] Patch (No new feature and no breaking change)
- [ ] Minor (New feature, but non breaking)
- [ ] Major (Breaking change)

## Have you bumped the package version?
- [ ] Yes
- [ ] No, does not need to be published

## Does this PR relate to an open issue?
- [ ] Yes (remember to link)
- [X ] No

## Have you added/updated the necessary tests?
- [X] Yes, only adjusted test, not added test for testing the highlighter functionality
- [ ] No, not needed

## Describe PR briefly:

Added Highlighter pipe to bold autocomplete options that matches the letters in the searchstring.

2020-01-30 14:45 UTC, frideska requested changes
Ser bra ut, fant en ting som fungerer litt rart: Hvis man prøver å velge et alternativ før man har søkt ferdig vil ikke selectoren velge alterativet ved klikk alltid, noen ganger fungerer det og andre ganger ikke! (funker fint med pil-taster)!

2020-02-03 08:13 UTC, JGH153 requested changes

2020-02-03 08:13 UTC, JGH153 commented on projects/hal-components/src/lib/components/autocomplete/highlight-autocomplete.pipe.spec.ts
> +  it('returns option with matching search term in bold', () => {
Lag en negativ test også + en som matcher to ganger

2020-02-04 09:36 UTC, JGH153 approved these changes

2020-02-04 09:37 UTC, frideska approved these changes

2020-02-04 09:39 UTC, merged