Date format
hafslundnett/hal-components pull request #38
Opened 2019-11-14 10:48 UTC by Martinesp

2019-11-18 09:26 UTC, JGH153 requested changes

2019-11-18 09:26 UTC, JGH153 commented on src/app/docs-pages/date-format-doc/date-format-doc.component.html
> +    Then in the root app.module providers, insert the object: {{ '{' }} provide: LOCALE_ID, useValue: 'nb' {{ '}' }}
Bør være highlighted, gjerne med det over

2019-11-18 09:26 UTC, JGH153 commented on src/app/docs-pages/date-format-doc/date-format-doc.component.ts
> +        result: formatDate(this.today, DateConstants[currentDate], 'nb')
Tror vi bør vurdere date fns

2019-11-18 09:26 UTC, JGH153 commented on src/app/shared/doc-api-table/doc-api-table.component.ts
> +  result = false;
?

2019-11-18 11:43 UTC, Martinesp commented on src/app/shared/doc-api-table/doc-api-table.component.ts
> +  result = false;
Fjerner det, antar det bare er noe jeg har glemt å fjerne

2019-11-19 09:38 UTC, JGH153 approved these changes

2019-11-19 09:38 UTC, merged