Quickstart & readme update
hafslundnett/hal-components pull request #63
Opened 2019-12-03 08:10 UTC by Martinesp

First draft of quickstart and update of welcome page

2019-12-10 14:53 UTC, JGH153 requested changes

2019-12-10 14:53 UTC, JGH153 commented on src/app/getting-started/getting-started.component.ts
> +  isSHELL = `ng add @hafslundnett/hal-components`;
isShell? addCommand

2019-12-10 14:53 UTC, JGH153 commented on src/app/getting-started/getting-started.component.ts
> +  isScss = `@import "~@hafslundnett/hdd-style/main";
isScss?

2019-12-10 14:53 UTC, JGH153 commented on src/app/getting-started/getting-started.component.scss
> +}
Er ikke disse allerede i styles.scss?

2019-12-10 14:53 UTC, JGH153 commented on src/app/getting-started/getting-started.component.html
> +    To add HAl simply open your terminal inside your project folder and copy the command from the
project root folder

2019-12-10 14:53 UTC, JGH153 commented on src/app/getting-started/getting-started.component.html
> +  <h2 class="doc-subtitle">Manual Installation HAL</h2>
Legg til: (Not recomende) til tittel

2019-12-10 14:53 UTC, JGH153 commented on src/app/getting-started/getting-started.component.html
> +  <ul style="margin-top: -25px; margin-left: 15px;">
Bytt til css klasse, og hvorfor minushverdier?

2019-12-10 14:53 UTC, JGH153 commented on src/app/getting-started/getting-started.component.html
> +  <p class="doc-info" style="margin-top: 15px;">
Ikke bruk style prop, bytt til klasse

2019-12-10 14:53 UTC, JGH153 commented on src/app/getting-started/getting-started.component.html
> +  <hal-divider style="margin: 25px 0px;"></hal-divider>
Ikke bruk style prop, bytt til klasse

2019-12-10 14:53 UTC, JGH153 commented on src/app/getting-started/getting-started.component.html
> +    <li>Npm: <span class="terminal-line">npm install @hafslundnett/hal-components</span></li>
Du må ogslå legge til HDD

2019-12-10 14:53 UTC, JGH153 commented on src/app/welcome/welcome.component.scss
> +  font-weight: 500;
Om den brukes i flere komponenter, legg den i styles.scss

2019-12-10 15:15 UTC, Martinesp commented on src/app/getting-started/getting-started.component.ts
> +  isSHELL = `ng add @hafslundnett/hal-components`;
Døpte om til shellCode så litt klarer hva det skal være

2019-12-10 15:15 UTC, Martinesp commented on src/app/getting-started/getting-started.component.ts
> +  isScss = `@import "~@hafslundnett/hdd-style/main";
Døpte om til scssCode så litt klarere hva det skal være

2019-12-10 15:17 UTC, Martinesp commented on src/app/getting-started/getting-started.component.scss
> +}
Fjernet nå

2019-12-10 15:19 UTC, Martinesp commented on src/app/welcome/welcome.component.scss
> +  font-weight: 500;
lag til i styles.sccss

2019-12-10 15:29 UTC, Martinesp commented on src/app/getting-started/getting-started.component.html
> +  <ul style="margin-top: -25px; margin-left: 15px;">
Den doc-infoen hadde litt mye luft, så ville bare tett lett inn. Men lagt om til klasser og fjernet minus margin

2019-12-11 07:49 UTC, JGH153 requested changes

2019-12-11 07:49 UTC, JGH153 commented on src/app/getting-started/getting-started.component.html
> +    You also need to have HDD-style installed, you can do this through yarn or npm:
De trenger også material, cdk + sette opp begge to

2019-12-12 10:04 UTC, JGH153 approved these changes

2019-12-12 11:09 UTC, merged