New selector
hafslundnett/hal-components pull request #65
Opened 2019-12-09 14:23 UTC by frideska

2019-12-10 07:56 UTC, JGH153 requested changes

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.scss
> +    font-size: 16px;
1 rem

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.scss
> +      font-size: 17px;
ikke 16? og bytt til rem

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.scss
> +      content: "\f107";
Legg inn kommentar på hva denne er (på samme linje ala: // arrow)

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.html
> +    <mat-select
disableOptionCentering fungerer, men da blir det alltid første valget som ligger over, men tror vi kan ha det sånn vi har det nå

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.html
> +    >
Støtter du å sette den til disabled? (både hele selecten og et enkelt element)

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.html
> +      <mat-option *ngFor="let data of selectData" [value]="data.value">
Vi må støtte multiple, men kan ta det i egen task om det ikke vil bli en breaking change

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.scss
> +.mat-select-panel {
Kan du løse dette med panelClass på mat-select?
https://material.angular.io/components/select/api
https://stackblitz.com/angular/onoyvojkmgm?file=src%2Fapp%2Fselect-panel-class-example.ts

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.html
> +    >
Støtter du required?

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.html
> +      (selectionChange)="onSelectedChange()"
Om den har en predefinert verdi vil den trigge en øyeblikkelig selectionChange?

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.html
> +      <mat-option *ngFor="let data of selectData" [value]="data.value">
Skulle ha støttet option groups, men kan ta i ny oppgave

2019-12-10 07:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.ts
> +  encapsulation: ViewEncapsulation.None
Bør wrappe css i egen klasse eller noe for å hindre lekarsjer

2019-12-10 12:29 UTC, frideska commented on projects/hal-components/src/lib/components/selector/selector.component.html
> +      (selectionChange)="onSelectedChange()"
Trigges ikke

2019-12-10 14:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.scss
> +  min-width: calc(100% + 29px);
29px? magisk tall bør ha kommentar

2019-12-10 14:56 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.scss
> +    width: 90%; // Find better solution! Mat-select adds 10% width, makes it overflow when taking 100% width
Har vi en bedre løsning?

2019-12-11 09:50 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.scss
> +      padding-right: 8px;
er ikke dette spacing-primary?

2019-12-12 07:53 UTC, JGH153 approved these changes

2019-12-12 08:52 UTC, merged