Pagination
hafslundnett/hal-components pull request #74
Opened 2019-12-12 13:31 UTC by frideska

2020-01-20 08:36 UTC, JGH153 requested changes

2020-01-20 08:36 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.ts
> +  someList: string[] = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25'];
Array.from(Array().keys(25))

2020-01-20 08:36 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.html
> +    </hal-paginator>
Om du gir den bare 3 elementer (someList) så bør alle valg som ikke gir mening i paginator sin pagesize fjernes. Tror mdm paginatoren allerede støtter dette

2020-01-20 08:36 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.scss
> +@import '~@hafslundnett/hdd-style/variables/colors';
kan fjerne

2020-01-20 08:36 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +    const alleVal: SelectData = {value: 'Alle', viewValue: 'Alle'};
Har du et bedre var navn på alleVal?

2020-01-20 08:36 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +    const alleVal: SelectData = {value: 'Alle', viewValue: 'Alle'};
og bør være under if statement under

2020-01-20 08:36 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +    pageSize === 'Alle' ? this.selectedPageSize = 10000 : this.selectedPageSize = +pageSize;
her er alle hardkodet til 10000 . Bør ha som default var eller noe

2020-01-20 08:36 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +    const alleVal: SelectData = {value: 'Alle', viewValue: 'Alle'};
og value bør ikke være Alle,

2020-01-20 08:36 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +    const alleVal: SelectData = {value: 'Alle', viewValue: 'Alle'};
og Alle som value bør være en const da den brukes senere

2020-01-20 08:36 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +        this.selectedPageSizeSelect = 'Alle';
Alle bør være en const og ikke magisk verdi

2020-01-20 08:36 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +      if (this.selectedPageSize === 10000) {
10000 er et magisk tall

2020-01-20 08:36 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +  private getAvailablePageSizes() {
return type

2020-01-20 08:36 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.ts
> +  changePaginator(changes?): void {
changes mangler type

2020-01-20 09:12 UTC, frideska commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +      if (this.selectedPageSize === 10000) {
Dette tallet var valgt fra før, men vet ikke om det er valgt pga noe mer enn at man tror det aldri kommer til å være mer verdier enn 10 000

2020-01-21 11:25 UTC, JGH153 requested changes

2020-01-21 11:25 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +  @Input() maxPageSize = DEFAULT_MAX_PAGE_SIZE;
Er ikke helt enig i navnet på denne 🤔  Kan virke som du setter hva største side/valg av pageSizeOptions som er lov. Hva med noe alla allOptionSize så skrive at den har en grense fortsatt, for å forhindre at du laster all data i universet på en gang

2020-01-21 11:25 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.ts
> +  someList: string[] = this.listOfNumbers.map(String);
Hvorfor konvertere til string?

2020-01-21 11:25 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.ts
> +  pageSizeOptions = [2, 5, 10, 25];
Om du starter med listOfNumbers på 2 elementer fjernes alle valg i paginatoren som ikke gir mening, men de kommer ikke tilbake om størrelsen blir større 🤔 

    setTimeout(() => {
      this.listOfNumbers = Array.from(Array(25).keys());
      this.someList = this.listOfNumbers.map(String);
      this.pagination.length = this.someList.length;
      this.slicedList = this.someList.slice(
        this.pagination.pageSize * this.pagination.pageIndex,
        this.pagination.pageSize * (this.pagination.pageIndex + 1)
      );
    }, 1000);
  }

2020-01-21 11:25 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +    this.setSelectOptions();
flytt til ngOnChanges

2020-01-21 11:25 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.ts
> +    });
skriv om til filter og map

2020-01-21 11:26 UTC, JGH153 commented on projects/hal-components/src/lib/components/paginator/paginator.component.spec.ts
> +describe('PaginatorComponent', () => {
lag en test som ser at du får tilbake alle alternativer om du går fra kort length til lang length

2020-01-23 11:18 UTC, frideska commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pagination](https://trello.com/c/xCXHnLCI/215-pagination)

2020-01-23 13:43 UTC, JGH153 requested changes

2020-01-23 13:43 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.html
> +    This way you give the user a sense of control by knowing where they are and they can estimate how much time it will take to find it.
Vurder noe ala:
Pagination enables tables content (client or serverside) to be dividet up into smaller pages that can be navigated using this paginator.

2020-01-23 13:43 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.html
> +      When there is a lot of content to process and the user is looking for specific information. Often used in conjunction with tables.
Noe ala: When a table with many rows needs to be dinviden into easier to handle pages

2020-01-23 13:43 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.html
> +      When the content is very visual.
When not a table?

2020-01-23 13:43 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.ts
> +    { apiInput: '[length]', description: 'The length of entries of your data' },
The number of elements (total) in your dataset

2020-01-23 13:43 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.ts
> +    { apiInput: '[unit]', description: 'Optional input to change name of elements to select between' },
Hva er default?

2020-01-23 13:43 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.ts
> +    { apiInput: '[selectedPageIndex]', description: 'Optional input sets selected page on index' },
page on index?

2020-01-23 13:43 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.ts
> +    { apiInput: '[allowAll]', description: 'Optional input to hide or show the "Alle" page size option. Is true by default' },
Bør si hva selecting the Alle option vil gi

2020-01-23 13:43 UTC, JGH153 commented on src/app/doc-pages/paginator-doc/paginator-doc.component.ts
> +    }, 1000);
trenger?

2020-01-27 09:33 UTC, JGH153 approved these changes

2020-01-27 09:33 UTC, merged