Select all
hafslundnett/hal-components pull request #94
Opened 2020-01-17 13:44 UTC by frideska

* Select all option
* Multiselect changes to have checkboxes, these are customized from the mat-select checkboxes, because using the hdd-checkboxes was very tricky

2020-01-20 08:17 UTC, JGH153 requested changes

2020-01-20 08:17 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.html
> +      [disabled]="isChoiceDisabled('Alle')"
Bør ikke kalle funksjon fra html uten pure pipe

2020-01-20 08:17 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.html
>        [disabled]="isChoiceDisabled(data.value)"
Bør ikke kalle funksjon fra html uten pure pipe

2020-01-20 08:17 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.ts
> +  @Input() selectAll = false;
kan selectAll  = true mens multipleChoices  = false?

2020-01-20 08:17 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.ts
> +      this.allSelected = true;
Dette bør vøre en funksjon, og kan det forekles?

2020-01-20 08:17 UTC, JGH153 commented on src/app/doc-pages/selector-doc/selector-doc.component.html
> +          [selectAll]="true"
Dette gjør neste eksempelet forvirrende (da du kan velge alle der, men får ikke alle). Bør finne på noe smart her 🤔

2020-01-20 08:17 UTC, JGH153 commented on projects/hal-components/src/lib/components/selector/selector.component.html
> +      [disabled]="isChoiceDisabled('Alle')"
samme for disabled over

2020-01-20 08:28 UTC, JGH153 commented
Bør selectData renames til selectOptions? selectData ble vanskerlig å forstå uten dokumentasjon

2020-01-20 09:59 UTC, frideska commented on projects/hal-components/src/lib/components/selector/selector.component.ts
> +  @Input() selectAll = false;
Ja er f.eks det man vil ha i paginatoren

2020-01-20 10:33 UTC, frideska commented on src/app/doc-pages/selector-doc/selector-doc.component.html
> +          [selectAll]="true"
Ja er forvirrende, men alle uten multipleChoices er jo at man velger det høyeste tallet, i multipleChoices velger man alle alternativene

2020-01-21 13:03 UTC, frideska commented on src/app/doc-pages/selector-doc/selector-doc.component.html
> +          [selectAll]="true"
'Marker alle' øverst

2020-01-23 10:52 UTC, Martinesp approved these changes

2020-01-23 11:24 UTC, frideska commented
![](https://github.trello.services/images/mini-trello-icon.png) [Selector: støtte for velgAlle (multiple) + checkboxes](https://trello.com/c/cf6WfmT6/244-selector-st%C3%B8tte-for-velgalle-multiple-checkboxes)

2020-01-23 13:34 UTC, JGH153 commented on src/app/doc-pages/selector-doc/selector-doc.component.ts
> +    // console.log('Some method was called: ' + selected);
?

2020-01-23 13:34 UTC, JGH153 commented
Bumber du minor version?

2020-01-24 13:28 UTC, JGH153 approved these changes

2020-01-27 07:03 UTC, merged